### ISSUE TITLE
Feedback 🎉 : provide a way to custom number of columns in home page

### ISSUE THREAD

**Issue by zachjmurphy** [fky2015/nexon#17]
First off, I just wanted to let you know that I am loving your template.

### Suggestion
It would be nice to define how many columns the blog home page could have. For example more than 3 columns etc.

**Comment by fky2015** [comment]
Thank you for your suggestions!

Are you referring to the gallery columns seen in the image below?

**CSS, in fact, is in charge of this behavior. As a result, making it a configurable option is a little tough. However, I'm planning to write a guide in the document on how to custom this.**

Does that sound good to you?

![image](https://user-images.githubusercontent.com/16451516/162112012-e5c3de88-7532-4c59-86b6-e72c93934abd.png)

The number of columns in the current main branch is set to one. I should admit that this assumption isn't appropriate for everyone, therefore I'll definitely make changes.

**Comment by zachjmurphy** [comment]
No problem, I am glad to provide a suggestion.

> Are you referring to the gallery columns seen in the image below?

Yes, I am referring to the gallery columns.

> CSS, in fact, is in charge of this behavior. As a result, making it a configurable option is a little tough. However, I'm planning to write a guide in the document on how to custom this.

A guide document on how to customize this would be great.

> Does that sound good to you?

This totally sounds great!

> The number of columns in the current main branch is set to one. I should admit that this assumption isn't appropriate for everyone, therefore I'll definitely make changes.

Okay awesome!

**Comment by fky2015** [comment]
I wrote a guide in [wiki](https://github.com/fky2015/nexon/wiki/Setup-&-Configuration#how-to-change-the-number-of-columns-on-the-gallery-view-17).

Hope it can help you out!

**Comment by zachjmurphy** [comment]
Awesome! Thank You.
