### ISSUE TITLE
Navigation Links

### ISSUE THREAD

**Issue by zachjmurphy** [fky2015/nexon#27]
#### Description

Hi, so I have recently been trying to add custom navigation links to my website. However, it seems that the "About" Notion Page is functional but the "Projects" & "Contact" are not working and instead just redirect to a 404 Page Not Found error. The "About", "Projects", and "Contact" pages are all public and have the same exact settings however the Projects, and Contact ones are not working. I am honestly about to give up on the navigation links. I really hope you might be able to help.

Thanks,
Zach

#### Notion Test Page ID

**About:**  913fde00aaa74f94a5cd3fb28a7890ff

**Projects:**  eecb4e6d98c247f9a8fcb71026aabd4a  **(Not Functional)**

**Contact:**  0076f5e0f9ec446a8160d77019608d46  **(Not Functional)**

**Comment by zachjmurphy** [comment]
Here is a link to the vercel instance: 

https://zachjmurphy-demo.vercel.app/

**Comment by zachjmurphy** [comment]
@fky2015 Just mentioning you in-case you didn't see this issue.

**Comment by fky2015** [comment]
Can you provide your `site.config.ts` so I can try to reproduce your problem?

It seems that you created these three pages in three different databases. As you can see, there'is a `rootNotionSpaceId` in the config. It will prevent rendering cross databases.

A good practice is nesting them together in a single database (just what it is in demo).

**Comment by zachjmurphy** [comment]
Sure! Here is my site.config.ts

```ts
import { siteConfig } from './lib/site-config'

export default siteConfig({
  // the site's root Notion page (required)
  rootNotionPageId: 'f41ace4892a842d2a2766e501b8aad77',

  // It's will be used as the root page when running `yarn dev`. (optional)
  // If you are suffering from the slow loading or compiling speed, set this to a smaller page.
  // Just leave `null` if you don't want to use it.
  rootNotionTestPageId: null,

  // if you want to restrict pages to a single notion workspace (optional)
  // (this should be a Notion ID; see the docs for how to extract this)
  rootNotionSpaceId: null,

  // basic site info (required)
  name: 'Zach J Murphy',
  domain: 'zachjmurphy.ca',
  author: 'Zach J Murphy',

  // open graph metadata (optional)
  description: 'Hello My name is Zach J Murphy. I do a bit of everything I make apps with SwiftUI, websites in Next.js and React, servers in Nodejs & Express.',

  // social usernames (optional)
  twitter: 'zachjmurphy',
  github: 'zachjmurphy',
  linkedin: null,

  // default notion icon and cover images for site-wide consistency (optional)
  // page-specific values will override these site-wide defaults
  defaultPageIcon: null,
  defaultPageCover: null,
  defaultPageCoverPosition: 0.5,

  // Giscus comments via Github Discusstion (optional)
  //
  // To generate the following configs, visit https://giscus.app/.
  giscusGithubConfig: {
    repo: 'zachjmurphy/zachjmurphy',
    repoId: 'R_kgDOHZ_AOg',
    category: 'Comments',
    categoryId: 'DIC_kwDOHZ_AOs4CPWDn',
    mapping: 'title',
    reactionsEnabled: '1',
    theme: 'light',
    term: null,
  },
  // whether or not to enable support for LQIP preview images (optional)
  isPreviewImageSupportEnabled: true,

  // whether or not redis is enabled for caching generated preview images (optional)
  // NOTE: if you enable redis, you need to set the `REDIS_HOST` and `REDIS_PASSWORD`
  // environment variables. see the readme for more info
  isRedisEnabled: false,

  // map of notion page IDs to URL paths (optional)
  // any pages defined here will override their default URL paths
  // example:
  //
  // pageUrlOverrides: {
  //   '/foo': '067dd719a912471ea9a3ac10710e7fdf',
  //   '/bar': '0be6efce9daf42688f65c76b89f8eb27'
  // }
  pageUrlOverrides: null,

  // Optional: Normally, the page contain it's metadata 
  // like `CreatedTime`, `LastEditedTime`.
  // These metadata cannot be changed by the user.
  // If you want to override this with a page property (so that 
  // you can custom it's value), specify it's name here.
  //
  // This should align with the property name in Notion.
  // And the data type should be `Date` or `String`.
  // Any invalid data type will be ignored and fallback to default metadata.
  //
  // These metadata will be used when generating RSS, Sitemap, etc.
  OverrideCreatedTime: null,
  OverrideLastEditedTime: null,

  // whether to use the default notion navigation style or a custom one with links to
  // important pages
  navigationStyle: 'custom',
  navigationLinks: [
    {
      title: 'About',
      pageId: '913fde00aaa74f94a5cd3fb28a7890ff'
    },
    {
      title: 'Projects',
      pageId: 'eecb4e6d98c247f9a8fcb71026aabd4a'
    },
    {
      title: 'Contact',
      pageId: '0076f5e0f9ec446a8160d77019608d46'
    }
  ]
})```

**Comment by zachjmurphy** [comment]
> Can you provide your `site.config.ts` so I can try to reproduce your problem?
> 
> It seems that you created these three pages in three different databases. As you can see, there'is a `rootNotionSpaceId` in the config. It will prevent rendering cross databases.
> 
> A good practice is nesting them together in a single database (just what it is in demo).

How would I put it into a single database?

**Comment by fky2015** [comment]
Just drag and move your page in the Notion navbar :smiley:.

![image](https://user-images.githubusercontent.com/16451516/170919427-3bdbe3c2-a1c6-49c8-8a6f-122cbd99dbe9.png)

As you can see in the demo, the ["Contact" page](https://nexon-demo.vercel.app/contact) is actually a subpage of the blog post. And the ["About" page](https://nexon-demo.vercel.app/about) is also a subpage (that is hiding in the database).

**Comment by fky2015** [comment]
In detail, Navigation Links is aimed to provide an alias to **processed pages**, which means all the pages in `rootNotionPageId`. Other pages, however, are not indexed by the project. So it's impossible to generate aliases because origin content does not exist.

**Comment by zachjmurphy** [comment]
> Just drag and move your page in the Notion navbar 😃.
> 
> ![image](https://user-images.githubusercontent.com/16451516/170919427-3bdbe3c2-a1c6-49c8-8a6f-122cbd99dbe9.png)
> 
> As you can see in the demo, the ["Contact" page](https://nexon-demo.vercel.app/contact) is actually a subpage of the blog post. And the ["About" page](https://nexon-demo.vercel.app/about) is also a subpage (that is hiding in the database).

Thank You. I will make this change.

**Comment by zachjmurphy** [comment]
> In detail, Navigation Link is aimed to provide an alias to **processed pages**, which means all the pages in `rootNotionPageId`. Other pages, however, are not indexed by the project. So it's impossible to generate aliases because origin content does not exist.

Thank you for the information.

**Comment by zachjmurphy** [comment]
> Just drag and move your page in the Notion navbar 😃.
> 
> ![image](https://user-images.githubusercontent.com/16451516/170919427-3bdbe3c2-a1c6-49c8-8a6f-122cbd99dbe9.png)
> 
> As you can see in the demo, the ["Contact" page](https://nexon-demo.vercel.app/contact) is actually a subpage of the blog post. And the ["About" page](https://nexon-demo.vercel.app/about) is also a subpage (that is hiding in the database).

I just made these changes and it fixed my problem. Thank You!
